language: node_js
node_js:
  - "8"
before_script:
  - npm install -g eslint
  #- npm install -g karma
script: true
  #- npm run build
  - npm run test
  #- npm run lint
repo_token: WroGd8H9HNosw0xe4qADgUa3MfSrueC2S